apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-app
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secure
  template:
    metadata:
      labels:
        app: secure
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        securityContext:
          privileged: false
          runAsNonRoot: true
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"